# source "https://rubygems.org"
# ruby "2.3.3"

# gem "sinatra"
# gem "sinatra-contrib"
# gem "unirest"
# gem "puma"
# gem "mongoid"
# gem "bson_ext"

source "https://rubygems.org"
ruby "2.3.3"

gem "sinatra", require: "sinatra/base"
gem "sinatra-contrib"
gem "puma"
gem "unirest"
gem "mongoid"
gem "bson_ext"
gem "rufus-scheduler"