development:
  clients:
    default:
      database: tvbot_development
      hosts:
        - localhost:27017
      options:
        consistency: strong

test:
  clients:
    default:
      database: tvbot_test
      hosts:
        - localhost:27017
      options:
        consistency: strong

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        skip_version_check: true
        safe: true
        consistency: strong